# nixpacks.toml
# Simple Railway configuration without problematic caching

[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x']

[phases.install]
cmds = ['npm install --legacy-peer-deps --production=false']

[phases.build]
cmds = [
    'npx prisma generate',
    'npx next build'
]

[start]
cmd = 'npm start'

# Disable problematic build caching
[variables]
NIXPACKS_NO_CACHE = "1"
