# nixpacks.toml
# Override Railway's default behavior

[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x']

[phases.install]
cmds = ['npm install --legacy-peer-deps --production=false']

[phases.build]
cmds = [
    'npx prisma generate',
    'npm run build'
]

[start]
cmd = 'npm start'
