[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x']

[phases.install]
cmds = ['npm install --production=false']

[phases.build]
cmds = [
    'npx prisma generate',
    'npm run build'
]

[start]
cmd = 'npm start'
